language: go

go:
  - 1.11.x

go_import_path: github.com/viktorburka/octopus

env:
  global:
    - secure: RpElq/p2LwbsCSMRuafgu2f95YlttVOG5B5+HgM4LQhgWg+NHJAMftOB5lC3mTln2MES0JVev7CyCvnSIIphIWBHrXpdrYbdCNC4+Z1Uv9TZsgf6haDwGz9k7lrD/XMXq0c0jXVdx6YHBnIwiY1CdhhskUKoqyAiNGnOoshOz35AXOEdnwnAgPDTL0puZKKHDtHWETbHIVOVxI3qIAdmVl3SMhVErTr82OJERIRrzJKEA+e0KZdp7JQ4Zw/yTKDAHnLheHTmjEgoqBHvylbdXeHdTZv7igoMwsO6TSPHbLgJ54Njx0YRt9wmO1iGh+ZrxI+LiyZg7eYIEFLZuSh3PUbAtXXCiMoA2FjQ5t8qg+75DMyBKgHj8kaAmfexVQIWUnAR7oerN9WwZZoVg8ewrIU13yZVxqKIsJ5Uzn0EDMBgDkgAmbmSExz9Ac/qxu813/b5azTjCs+Jqt41M/TlDFPYBFomuULOtAVK34jTvg6NuC4mHEFgaxjLhpyI2WXa7U0R4/LV/7/+btf8JcyhZIiq+D5R8ymJpqoeQtsNVDpiDRymoMfb4YbcuqoX1Q/zDRUvhqbLL1n02lEAOwjGcAW/ASPlAOf3SDZe7DvXQ4G64lw3dVpNOxoJ9Cr2efgpDhJQNDMjs36uTGeAyGk3LbAGOOrfMAlxoF8wsPsc3GA=

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go get -d -v ./...
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
